import { UploadFootageDialog } from "@/components/UploadFootageDialog";
import { Button } from "@/components/ui/button";
import { demoImages } from "@/lib/footage";
import { ArrowDownRight, ArrowUpRight, BookOpenText, Clapperboard, FolderHeart, ImageUp, MessageCirclePlus, Search, Sparkles, WandSparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const featureCards = [
  { title: "Look again", note: "Search footage like you remember it — by light, colour, place, feeling, or motion.", icon: Search, href: "/library", tone: "note-yellow" },
  { title: "Keep threads", note: "Collect the clips that begin to feel like they belong together.", icon: FolderHeart, href: "/collections", tone: "note-green" },
  { title: "Think with it", note: "Ask a focused creative question about the material you have already selected.", icon: MessageCirclePlus, href: "/ask", tone: "note-blue" },
];

export default function Home() {
  const [uploadOpen, setUploadOpen] = useState(false);
  return <div className="app-glow min-h-screen overflow-x-hidden ink"><UploadFootageDialog open={uploadOpen} onOpenChange={setUploadOpen} />
    <header className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><div className="grid size-10 -rotate-6 place-items-center rounded-[14px] border-[1.5px] border-[#2c2922] bg-[#f4ad89] shadow-[2px_3px_0_#2c2922]"><Clapperboard className="size-4" /></div><div><p className="font-hand text-2xl font-bold leading-none">framefind</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[.18em] ink-muted">footage sketchbook</p></div></Link><nav className="hidden items-center gap-6 text-sm ink-muted sm:flex"><Link href="/library" className="hover:text-[#2c2922]">Sample</Link><Link href="/docs" className="hover:text-[#2c2922]">How it works</Link><button onClick={() => setUploadOpen(true)} className="font-semibold text-[#2c2922] underline decoration-wavy decoration-[#e69275] underline-offset-4">Upload footage</button></nav><Button onClick={() => setUploadOpen(true)} className="h-10 -rotate-1 rounded-xl border-[1.5px] border-[#2c2922] bg-[#f4ad89] px-3 text-xs font-bold text-[#2c2922] shadow-[2px_2px_0_#2c2922] hover:bg-[#fac7ae] sm:hidden"><ImageUp className="size-4" /></Button></header>
    <main className="mx-auto max-w-[1280px] px-5 pb-16 sm:px-8"><section className="grid items-center gap-10 py-11 lg:grid-cols-[1.04fr_.96fr] lg:py-20"><div className="reveal"><p className="inline-flex rotate-[-1deg] items-center gap-2 rounded-md border border-[#2c2922]/35 bg-[#fff1ba] px-2.5 py-1 font-mono text-[10px] uppercase tracking-[.16em]"><Sparkles className="size-3" />For the footage before the edit</p><h1 className="mt-6 max-w-2xl font-hand text-[58px] font-bold leading-[.84] tracking-[-.055em] sm:text-[82px]">Find the story<br />hiding <span className="scribble">in your clips.</span></h1><p className="mt-7 max-w-xl text-base leading-7 ink-muted">Framefind is an AI-powered footage sketchbook for the uncertain beginning: the moment when you have a phone full of material, but no clear idea what it could become.</p><p className="mt-4 font-hand text-2xl font-semibold">Less hunting. More noticing.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/library" className="inline-flex h-11 items-center gap-2 -rotate-[.7deg] rounded-xl border-[1.5px] border-[#2c2922] bg-[#f8d9cc] px-4 text-sm font-bold shadow-[3px_3px_0_#2c2922] transition-transform hover:-translate-y-0.5">Explore the sample <ArrowUpRight className="size-4" /></Link><Button onClick={() => setUploadOpen(true)} variant="outline" className="h-11 rounded-xl border-[1.5px] border-[#2c2922]/60 bg-[#fffdf7] px-4 text-sm font-semibold text-[#2c2922] hover:bg-[#dcefdc]"><ImageUp className="mr-2 size-4" />Upload your footage</Button></div><p className="mt-4 text-[11px] ink-muted">The sample is a safe, read-only playground. Uploading asks you to sign in first.</p></div>
      <div className="reveal relative mx-auto w-full max-w-[520px] lg:ml-auto"><div className="tape paper-panel rotate-[1.4deg] overflow-hidden rounded-[26px] p-3"><div className="relative aspect-[4/3] overflow-hidden rounded-[18px] border-[1.5px] border-[#2c2922]/55"><img src={demoImages[104]} alt="Rainy night city footage example" className="h-full w-full object-cover" /><div className="absolute inset-x-4 bottom-4 flex items-center justify-between"><span className="rounded bg-[#fffdf7]/90 px-2 py-1 font-mono text-[10px] shadow-sm">IMG_4902.MOV</span><span className="rounded bg-[#f8d9cc] px-2 py-1 text-[10px] font-semibold shadow-sm">quiet · blue · night</span></div></div><div className="flex items-center justify-between px-2 py-3"><div><p className="font-hand text-2xl font-bold">A moment, annotated.</p><p className="text-[11px] ink-muted">Turn a fuzzy memory into a way back to the clip.</p></div><WandSparkles className="size-5 text-[#bd7058]" /></div></div><div className="note-green absolute -bottom-5 -left-5 rotate-[-6deg] rounded-xl border-[1.5px] border-[#2c2922]/55 px-4 py-3 text-sm font-semibold shadow-[3px_3px_0_rgba(44,41,34,.14)]">“Find me the quiet<br />blue night shots.”</div><div className="note-yellow absolute -right-3 top-12 rotate-[6deg] rounded-lg border border-[#2c2922]/45 px-3 py-2 font-hand text-lg font-bold shadow-[2px_2px_0_rgba(44,41,34,.12)]">the clue is a feeling</div></div></section>
      <section className="border-y-[1.5px] border-[#2c2922]/45 py-12"><div className="grid gap-6 md:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] ink-muted">What it is</p><h2 className="mt-3 font-hand text-4xl font-bold leading-[.92]">Not another editor.</h2><p className="mt-4 max-w-sm text-sm leading-6 ink-muted">Framefind sits before the timeline. It makes your raw material easier to understand, retrieve, group, and talk through.</p></div><div className="grid gap-3 sm:grid-cols-3">{featureCards.map(card => { const Icon = card.icon; return <Link key={card.title} href={card.href} className={`sketch-card ${card.tone} rounded-2xl border-[1.5px] border-[#2c2922]/52 p-4`}><Icon className="size-5" /><h3 className="mt-8 font-hand text-2xl font-bold">{card.title}</h3><p className="mt-2 text-xs leading-5 ink-muted">{card.note}</p><span className="mt-5 inline-flex items-center gap-1 text-[11px] font-semibold">Open feature <ArrowDownRight className="size-3" /></span></Link>; })}</div></div></section>
      <section className="grid gap-5 py-14 lg:grid-cols-[1.1fr_.9fr]"><div className="paper-panel rounded-2xl p-7"><p className="font-mono text-[10px] uppercase tracking-[.18em] ink-muted">Start here</p><ol className="mt-5 space-y-4"><li className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-[#2c2922]/45 bg-[#f8d9cc] font-hand text-lg font-bold">1</span><div><p className="text-sm font-bold">Explore the sample.</p><p className="mt-1 text-xs leading-5 ink-muted">Try a feeling-first search and use Find Similar without touching your own files.</p></div></li><li className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-[#2c2922]/45 bg-[#dcefdc] font-hand text-lg font-bold">2</span><div><p className="text-sm font-bold">Upload a small set of clips.</p><p className="mt-1 text-xs leading-5 ink-muted">Framefind creates a first layer of visual notes from one representative frame.</p></div></li><li className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-[#2c2922]/45 bg-[#e8eff7] font-hand text-lg font-bold">3</span><div><p className="text-sm font-bold">Circle, collect, and ask.</p><p className="mt-1 text-xs leading-5 ink-muted">Turn promising footage into a collection, then ask a specific creative question.</p></div></li></ol></div><div className="tape note-blue rotate-[.5deg] rounded-2xl border-[1.5px] border-[#2c2922]/52 p-7 shadow-[3px_3px_0_rgba(44,41,34,.14)]"><BookOpenText className="size-6" /><h2 className="mt-8 font-hand text-4xl font-bold leading-[.9]">A guide is part<br />of the product.</h2><p className="mt-4 text-sm leading-6 ink-muted">Read the documentation to understand each feature, the difference between sample and personal footage, and what the current prototype does with your files.</p><Link href="/docs" className="mt-6 inline-flex items-center gap-2 rounded-lg border-[1.5px] border-[#2c2922]/55 bg-[#fffdf7] px-3 py-2 text-xs font-bold shadow-[2px_2px_0_rgba(44,41,34,.12)]">Open documentation <ArrowUpRight className="size-3.5" /></Link></div></section>
    </main>
  </div>;
}
